---
- id: docker-compose-check
  name: Validate docker compose files
  description: Checks that docker compose files are valid
  language: python
  entry: compose_check
  files: (docker-)?compose\.ya?ml$
